// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_sandbox/test/unit2_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_webrtc/flutter_webrtc.dart' as _i3;
import 'package:flutter_webrtc/src/interface/rtc_video_renderer.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeVideoRenderer_0 extends _i1.Fake implements _i2.VideoRenderer {}

/// A class which mocks [RTCVideoRenderer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCVideoRenderer extends _i1.Mock implements _i3.RTCVideoRenderer {
  MockRTCVideoRenderer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VideoRenderer get delegate =>
      (super.noSuchMethod(Invocation.getter(#delegate),
          returnValue: _FakeVideoRenderer_0()) as _i2.VideoRenderer);
  @override
  set onResize(Function? func) =>
      super.noSuchMethod(Invocation.setter(#onResize, func),
          returnValueForMissingStub: null);
  @override
  int get videoWidth =>
      (super.noSuchMethod(Invocation.getter(#videoWidth), returnValue: 0)
          as int);
  @override
  int get videoHeight =>
      (super.noSuchMethod(Invocation.getter(#videoHeight), returnValue: 0)
          as int);
  @override
  bool get renderVideo =>
      (super.noSuchMethod(Invocation.getter(#renderVideo), returnValue: false)
          as bool);
  @override
  bool get muted =>
      (super.noSuchMethod(Invocation.getter(#muted), returnValue: false)
          as bool);
  @override
  set muted(bool? mute) => super.noSuchMethod(Invocation.setter(#muted, mute),
      returnValueForMissingStub: null);
  @override
  set audioOutput(String? deviceId) =>
      super.noSuchMethod(Invocation.setter(#audioOutput, deviceId),
          returnValueForMissingStub: null);
  @override
  set srcObject(_i3.MediaStream? stream) =>
      super.noSuchMethod(Invocation.setter(#srcObject, stream),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(Invocation.method(#initialize, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
